# This is to override the chart name.
nameOverride: "db"
fullnameOverride: "db"

# ReplicaSet pod count
replicaCount: 1

# Additional labels to add to all objects
additionalLabels:
  app: db

image:
  # Application image repository
  repository: postgres
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Application image tag
  tag: 15-alpine

# Container environment variables
environment:
  - name: POSTGRES_USER
    value: postgres
  - name: POSTGRES_PASSWORD
    value: postgres

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext: {}
  # runAsNonRoot: true
  # seccompProfile:
  #   type: "RuntimeDefault"

# Container security context
securityContext: {}
  # privileged: false
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop: ["ALL"]
  # readOnlyRootFilesystem: true

# Liveness and readiness probes
livenessProbe:
  tcpSocket:
    port: 5432
readinessProbe:
  tcpSocket:
    port: 5432

# Container resources
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Set affinity (poAffinity, podAntiAffinity, nodeAffinity)
affinity: {}

# Service settings
service:
  # Service type
  type: ClusterIP
  # Service port
  port: 5432
  # Container port
  targetPort: 5432
  # Container port
  protocol: TCP

# Additional Volumes
volumes:
  - name: db-data
    emptyDir: {}

# Additional volume mounts.
volumeMounts:
  - mountPath: /var/lib/postgresql/data
    name: db-data
