# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# ReplicaSet pod count
replicaCount: 1

# Additional labels to add to all objects
additionalLabels:
  app: redis

image:
  # Application image repository
  repository: redis
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Application image tag
  tag: 8.2.2

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: "RuntimeDefault"

# Container security context
securityContext:
  privileged: false
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
  runAsUser: 999
  runAsGroup: 999

# Liveness and readiness probes
livenessProbe:
  tcpSocket:
    port: 6379
readinessProbe:
  tcpSocket:
    port: 6379

# Container resources
resources:
  limits:
    # cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Set affinity (poAffinity, podAntiAffinity, nodeAffinity)
affinity: {}

# Service settings
service:
  # Service type
  type: ClusterIP
  # Service port
  port: 6379
  # Container port
  targetPort: 6379
  # Container port
  protocol: TCP

# Additional Volumes
volumes:
  - name: redis-data
    emptyDir: {}

# Additional volume mounts.
volumeMounts:
  - mountPath: /data
    name: redis-data
